id: introduction
name: Introduction
description: Learn how to use the Prelude Operator from start to finish
courses:
  - name: orientation
    description: Explore and understand the terminology and Operator interface
    challenges:
      - 00000000-0000-0000-0000-000000000001
      - 50bcb70f-86c8-4b62-aa58-611831866173
      - 2080e0e3-f107-418d-8a9f-773fe2d7fb04
      - 29560d69-8ccb-45b4-a4ca-06b2b14fae02
      - fc7e65a1-7c08-4aec-a247-aefe15477b98
      - e573a081-0fc3-49b3-b039-cd72e3772a62
      - be82d7a7-bb60-47a0-834d-655318c08369
  - name: basic deployment
    description: Discover the use of editor and stockpile of available TTPs
    challenges:
      - 326c369e-4672-48c1-9120-2fdd3a13d80d
      - 1655c859-17dd-4b53-9ae6-3e895afb8cc7
      - 3abff28a-e1c0-498f-a273-0ab8e627d122
      - 9a6caab1-13a1-4b44-9eb4-b4994d860863
  - name: understanding agents
    description: Deploy, configure and learn the capabilities of agents
    challenges:
      - 79c1cf88-b321-45af-a157-a245de29ddc0
      - ff6a1861-edf1-41a1-b00f-7a3d3ed58545
      - 7ad84c09-dfa9-431d-a273-908cdbacbae2
      - 2f801418-a956-43cc-8a21-504c0ce5b602
      - c276c08c-2eb0-4dfe-b542-91e8409c60ab
      - 8fb4c5f2-2be1-4f54-a330-061992cc8a4f
      - 9e7b2d08-21bd-4244-ab46-243d597e5d29
  - name: advanced deployment
    description: Creating and managing procedures to launch against agents
    challenges:
      - 5dcf668b-b3ad-4ee5-b595-c716baf79b2c
      - 0b044323-bf6b-4856-8d70-372942983aab
      - 2aac8660-191d-4617-a0b4-a02de8d19364
      - 9112f8d6-4ee1-4582-bd55-d42519cec783
      - 2a729508-8410-4ea8-924d-a6ddd14fd64d
      - 16e97188-0b7e-4a45-90f6-1c9852573944
